name: build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x', '24.x']

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm test

      - run: npm run build

      - run: npm pack
